on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
        rustup target add x86_64-apple-darwin aarch64-apple-darwin
        cargo build --release --target=x86_64-apple-darwin
        cargo build --release --target=aarch64-apple-darwin
        ls -lah
        lipo target/{x86_64,aarch64}-apple-darwin/release/actions-macos-universal-test -create -output actions-macos-universal-test
      - uses: actions/upload-artifact@v2
        with:
          name: actions-macos-universal-test
          path: actions-macos-universal-test